    deployment:
  tasks:
    - export DEPLOYPATH=/home/anna1557/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -r Image $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
